---
# vars file for common-host-config
#docker yml vars
CTOP_VERSION: "0.7.3"
DOCKER_COMPOSE_VERSION: "1.25.1"
DOCKER_PACKAGES:
 - apt-transport-https
 - ca-certificates
 - curl
 - gnupg-agent
 - software-properties-common
USER: "ubuntu"


apt_packages:
  - python3-pip
  - tmux
  - tmate
