plugin: aws_ec2
region: us-east-2
filters:
 tag:env: "prod"
 instance-state-name: "running"
keyed_groups:
  - key: tags.Name
    prefix: name
  - key: tags.role
    prefix: role
hostnames:
  - network-interface.association.public-ip
