---
# tasks file for grafana-host-config
#
- name: create the directory structure
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ app_paths }}"
  ignore_errors: yes

- name: check to see if grafana isn't already running
  become: yes
  shell: docker container ls  
  register: list

- debug:
   msg: "{{ list.stdout }}"

- name: pulling down grafana docker container
  become: yes
  shell: docker container run -d -p 3000:3000 --name grafana grafana/grafana && docker container ls
  register: grafana

- name: debug grafana deployment
  debug:
    var: grafana



