---
# tasks file for prometheus-host-config
#
- name: create the directory structure
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ app_paths }}"
  ignore_errors: yes

- name: moving promtheus.yml
  template:
    src: prometheus.yml
    dest: /home/ubuntu/app/conf/prometheus.yml

- name: checking to see for existing prometheus docker
  become: yes
  shell: docker container ls
  register: list

- debug:
   msg: "{{ list.stdout }}"

- name: pulling down prometheus docker container
  become: yes
  shell: docker container run -d -p 9090:9090 -v /home/ubuntu/app/conf/prometheus.yml:/etc/prometheus/prometheus.yml --name prometheus prom/prometheus && docker container ls
  register: prometheus

- name: debug prometheus deployment
  debug:
    var: prometheus



